version: "3.9"

services:
  php:
    build:
      context: ./.docker/php
    container_name: project_php
    volumes:
      - ./:/var/www/html:cached
    networks:
      - app-network

  nginx:
    build:
      context: ./.docker/nginx
    container_name: project_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www/html:cached
    networks:
      - app-network
    depends_on:
      - php

  postgres:
    image: postgres:latest
    container_name: project_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - app-network

  node:
    image: node:16
    container_name: project_node
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: tail -f /dev/null

volumes:
  pgdata:

networks:
  app-network:
